#!/usr/bin/env python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../util")
from build_tools import *

# Target: STM32H523xC (Cortex-M33 @ 250 MHz, 4 input-capture channels).
#
# Clock: 10 MHz active oscillator (rubidium / GPS-disciplined) on OSC_IN
# via HSE bypass, multiplied by PLL to 250 MHz SYSCLK.
#   HSE 10 MHz / PLLM=1 = 10 MHz VCI
#   10 MHz * PLLN=50    = 500 MHz VCO
#   500 MHz / PLLP=2    = 250 MHz SYSCLK    (PLLP is hardcoded to 2)
# On H5 the PLLM/PLLN fields are raw integers, unlike G4 which wants
# RCC_PLLM_DIVn macros.
RulosBuildTarget(
    name = "timestamper",
    sources = ["timestamper.c", "scpi.c"],
    peripherals = "uart usb-cdc-stm32 scpi",
    platforms = [
        ArmStmPlatform(
            "stm32h523xc",
            extra_cflags = [
                '-DHSE_VALUE=10000000',
                '-DRULOS_USE_HSE',
                '-DRULOS_HSE_BYPASS',
                '-DRULOS_PLLM=1',
                '-DRULOS_PLLN=50',
                '-DSCHEDULER_CAPACITY=4',
                # USB identity (pid.codes registration pending; see
                # https://github.com/pidcodes/pidcodes.github.com/pull/1201).
                # Note: this drops the cdc_acm DISABLE_ECHO quirk that the
                # default 0x0424:0x274e gets on Linux. Re-test if echo issues
                # reappear.
                '-DUSBD_VID=0x1209',
                '-DUSBD_PID=0x71C4',
                '-DUSBD_PRODUCT_STRING=\\"LectroTIC-4\\"',
                '-DUSBD_SERIAL_PREFIX=\\"LT4-\\"',
            ],
        ),
    ],
).build()
