#!/bin/sh

# Auto-formats all code that ends in .c or .h that's been changed in subversion.
# I should have called it "g4 fix".

filelist1=`git diff --relative --name-only | grep '.*\.h$\|.*\.c$' | grep -v vendor_libraries`
filelist2=`git diff --cached --relative --name-only | grep '.*\.h$\|.*\.c$' | grep -v vendor_libraries`
filelist="$filelist1 $filelist2"

if [ -z "$filelist" ]; then
    echo No changed files
    exit
fi

clang-format -i --verbose $filelist
dos2unix $filelist
chmod ugo-x $filelist

exit

# Or, to autoformat everything, remove the exit above
find . -name '*.[ch]' -type f -print \
    | fgrep -v /obj. \
    | grep -v vendor_libraries \
    | xargs clang-format -i --style=google --verbose

