import sys
import os
sys.path.insert(0, "../../../util")
from build_tools import *
from build_tools import util

RulosBuildTarget(
    name = "gpio-test",
    sources = ["gpio-test.cpp"],
    extra_cflags = [
        "-DLOG_TO_SERIAL",

        # include out-of-repo directory to get wifi credentials
        "-I" + os.path.expanduser("~/.config/rulos")
    ],
    peripherals = ["uart", "inet", "ntp"],
    platforms = [
        Esp32Platform(),
    ],
).build()

# "Manual" build of the test suite for the NTP linear regression code.
env = Environment()
build_dir = os.path.join(util.BUILD_ROOT, "regression-test")
env.VariantDir(build_dir, util.PROJECT_ROOT, duplicate=0)
env.Append(CCFLAGS=[
    "-DKEEP_SYSTEM_ASSERT",
    "-DSIMULATOR",
])
env.Append(CPPPATH=[
    "../../../lib",
    "../../../lib/chip/esp32",
])
Default(env.Program(os.path.join(build_dir, "regression-test"), source=[
    os.path.join(build_dir, "src/lib/chip/esp32/periph/ntp/regression.cpp"),
    os.path.join(build_dir, "src/app/tests/ntp/regression-test.cpp"),
]))
