#!/usr/bin/env python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../util")
from build_tools import *

# Target: STM32G474xE (Cortex-M4F, LQFP64; HRTIM + GP timers drive 4 channels).
#
# Clock: 10 MHz active oscillator (rubidium / GPS-disciplined) on OSC_IN
# via HSE bypass, multiplied by PLL to 125 MHz SYSCLK.
#   HSE 10 MHz / PLLM=1 = 10 MHz VCI
#   10 MHz * PLLN=25    = 250 MHz VCO
#   250 MHz / PLLR=2    = 125 MHz SYSCLK   (PLLR fixed at /2 in stm32-hardware)
# fHRTIM = 125 MHz; HRTIM DLL gives 32x oversampling = 4 GHz (250 ps/tick)
# at the finest CKPSC. PLLM/PLLN are RCC_PLLM_DIVn macros on G4 (unlike H5).
RulosBuildTarget(
    name = "pulsegen",
    sources = ["pulsegen.c", "scpi.c"],
    peripherals = "uart usb-cdc-stm32 scpi",
    platforms = [
        ArmStmPlatform(
            "stm32g474xe",   # LQFP64 RE: 512 KB flash, 96 KB SRAM
            extra_cflags = [
                '-DHSE_VALUE=10000000',
                '-DRULOS_USE_HSE',
                '-DRULOS_HSE_BYPASS',
                # Rev B: PA9/PA10 are channel outputs, so the debug UART (USART1)
                # moves to PB6 (TX) / PB7 (RX) -- both USART1 AF7, both free.
                '-DRULOS_UART0_TX_PIN=GPIO_B6',
                '-DRULOS_UART0_RX_PIN=GPIO_B7',
                '-DRULOS_PLLM=RCC_PLLM_DIV1',
                '-DRULOS_PLLN=25',
                '-DSCHEDULER_CAPACITY=8',
                '-DUSBD_VID=0x1209',
                '-DUSBD_PID=0x71C5',
                '-DUSBD_PRODUCT_STRING=\\"PG-4\\"',
                '-DUSBD_SERIAL_PREFIX=\\"PG4-\\"',
            ],
        ),
    ],
).build()
