#!/usr/bin/env python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../util")
from build_tools import *

# Target: STM32G474xB (Cortex-M4F, has HRTIM, 2 output channels).
#
# Clock: 10 MHz active oscillator (rubidium / GPS-disciplined) on OSC_IN
# via HSE bypass, multiplied by PLL to 125 MHz SYSCLK.
#   HSE 10 MHz / PLLM=1 = 10 MHz VCI
#   10 MHz * PLLN=25    = 250 MHz VCO
#   250 MHz / PLLR=2    = 125 MHz SYSCLK   (PLLR fixed at /2 in stm32-hardware)
# fHRTIM = 125 MHz; HRTIM DLL gives 32x oversampling = 4 GHz (250 ps/tick)
# at the finest CKPSC. PLLM/PLLN are RCC_PLLM_DIVn macros on G4 (unlike H5).
RulosBuildTarget(
    name = "pulsegen",
    sources = ["pulsegen.c", "scpi.c"],
    peripherals = "uart usb-cdc-stm32 scpi",
    platforms = [
        ArmStmPlatform(
            "stm32g474xe",   # LQFP64 RE: 512 KB flash, 96 KB SRAM
            extra_cflags = [
                '-DHSE_VALUE=10000000',
                '-DRULOS_USE_HSE',
                '-DRULOS_HSE_BYPASS',
                '-DRULOS_PLLM=RCC_PLLM_DIV1',
                '-DRULOS_PLLN=25',
                '-DSCHEDULER_CAPACITY=8',
                # USB VID/PID under pid.codes (0x1209). 0x71C5 neighbors the
                # timestamper's 0x71C4 (LectroTIC-4). DFU support is auto-
                # included by the usb-cdc-stm32 peripheral; this PID is what
                # dfu-util -d targets to send a DFU_DETACH.
                '-DUSBD_VID=0x1209',
                '-DUSBD_PID=0x71C5',
                # USB iSerialNumber descriptor prefix: <prefix><24-hex UID>.
                # Also appears in the *IDN? serial field (built in the SCPI
                # library from usbd_cdc_get_serial()).
                '-DUSBD_SERIAL_PREFIX=\\"PG-\\"',
            ],
        ),
    ],
).build()
