#!/usr/bin/python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../../build-tools")
from BuildRules import *

RulosBuildTarget(
  name = "audioboard",
  sources = ["audioboard.c"],
  extra_cflags = ["-DLOG_TO_SERIAL", "-DRULOS_I2C_ALT_MAPPING"],
  platforms = [
    SimulatorPlatform(
        extra_cflags=[],
        extra_peripherals = "pseudosdcard",
    ),
    ArmStmPlatform("stm32f303xb",
        extra_cflags=[
            "-DBOARD_RULOS_AUDIO_REV_B",
            "-DBOARDCONFIG_UNIROCKET",
        ],
        extra_peripherals = "sdcard2 twi",
    ),
  ],
  peripherals = "uart audio i2s fatfs".split(),
  ).build()
