#!/usr/bin/env python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../../util")
from build_tools import *

# STM32 families on which RULOS has implemented a TWI driver (see
# src/lib/chip/arm/stm32/periph/twi/twi.c). twisendtest.c is the only
# self-contained test (it calls hal_twi_init directly) so it's the
# one built against stm32.
# F0 and G0 are excluded: twi.c's F0/G0 branches have always had
# dead chip-specific stubs (wrong GPIO alt-func, missing IRQn macros)
# and no RULOS app has ever compiled twi on those families.
TWI_SUPPORTED_STM32_FAMILIES = (
    "STM32F1",
    "STM32F3",
)
stm32_twi_platforms = [
    ArmStmPlatform(chip_name)
    for chip_name in sorted(ArmStmPlatform.CHIPS)
    if ArmStmPlatform.CHIPS[chip_name].major_family_name
    in TWI_SUPPORTED_STM32_FAMILIES
]

RulosBuildTarget(
    name = "twirecvtest",
    sources = [ "twirecvtest.c" ],
    platforms = [
        SimulatorPlatform(),
        AvrPlatform(
            "atmega328p",
            extra_peripherals = "twi 7seg_panel_hardware",
        ),
    ],
    peripherals = "7seg_panel",
    extra_cflags = [
        "-DBOARD_DONGLE_REVB",
        "-DBOARDCONFIG_DEFAULT",
    ],
).build()

RulosBuildTarget(
    name = "twisendtest",
    sources = [ "twisendtest.c" ],
    platforms = [
        SimulatorPlatform(),
        AvrPlatform(
            "atmega328p",
            extra_peripherals = "twi 7seg_panel_hardware",
        ),
    ],
    peripherals = "7seg_panel",
    extra_cflags = [
        "-DBOARD_PCB11",
        "-DBOARDCONFIG_DEFAULT",
        "-DSTATUS_TO_LOCAL_PANEL",
    ],
).build()

# STM32 canary build: twisendtest without the 7seg_panel status hack.
# twirecvtest depends on network-layer reassembly that's not wired up
# on stm32 here; twisendtest just needs hal_twi_init + send.
RulosBuildTarget(
    name = "twisendtest_stm32",
    sources = [ "twisendtest.c" ],
    platforms = stm32_twi_platforms,
    peripherals = "twi",
).build()
