#!/usr/bin/python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../util")
from build_tools import *

apps = [
    {
        'name': 'datalogger',
        'board': 'BOARD_DATALOGGER_REV_B',
    },
    {
        'name': 'ltetag-dev1',
        'board': 'BOARD_LTETAG_DEV_REV_A',
    },
]

for app in apps:
    RulosBuildTarget(
        name = app['name'],
        sources = [
            "curr_meas.c",
            "flash_dumper.c",
            "ina219.c",
            "serial_reader.c",
            f"{app['name']}.c",
        ],
        platforms = [
            ArmStmPlatform("stm32g0b1xe",
                extra_cflags=[
                    f"-D{app['board']}",
                    "-DUART_RX_QUEUE_LEN=4096",
                ],
            )],
        peripherals = "uart sdcard2 fatfs",
        extra_cflags = [
            "-DLOG_TO_SERIAL",
        ],
    ).build()
