#!/usr/bin/python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../util")
from build_tools import *

apps = [
    {
        'name': 'datalogger',
        'board': 'BOARD_DATALOGGER_REV_B',
        'extra_sources': ["ina219.c"],
    },
    {
        'name': 'ltetag-dev1',
        'board': 'BOARD_LTETAG_DEV_REV_A',
        'extra_sources': ["ina219.c"],
        'extra_cflags': [
            "-DUSART2_RX_ON_A15",
            "-DUSART5_RX_ON_B4",
        ],
    },
    {
        'name': 'gemini-logger',
        'board': 'BOARD_GEMINI_DATALOGGER_REV_A',
    },
]

for app in apps:
    RulosBuildTarget(
        name = app['name'],
        sources = app.get('extra_sources', []) + [
            "curr_meas.c",
            "flash_dumper.c",
            "serial_reader.c",
            f"{app['name']}.c",
        ],
        platforms = [ArmStmPlatform("stm32g0b1xe")],
        peripherals = "uart sdcard2 fatfs",
        extra_cflags = app.get('extra_cflags', []) + [
            f"-D{app['board']}",
            "-DLOG_TO_SERIAL",
            "-DLINEREADER_MAX_LINE_LEN=4096",
            "-DUART_TX_QUEUE_LEN=4096",
            "-DUART_RX_QUEUE_LEN=8192",

            # don't use these DMA channels for UART RX, since they're
            # used by the SD card
            "-DUART_SURRENDER_DMA1_CHAN2_3",
        ],
    ).build()
