#!/usr/bin/python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../../util")
from build_tools import *

platforms = []

for chip in [
        "stm32f103x8",
        "stm32f031x6",
        "stm32f303x8",
        "stm32g031x8",
        "stm32g0b1xe",
        "stm32g431x8",
]:
    platforms.append(ArmStmPlatform(chip))

for chip in [
        "atmega328",
        "atmega328p",
        "atmega1284",
#        "attiny84",
#        "attiny85",
]:
    platforms.append(AvrPlatform(chip))

platforms.append(Esp32Platform())

for testprog in ["recv", "send", "charecho", "lineecho"]:
    RulosBuildTarget(
        name = testprog,
        sources = [f"{testprog}.c"],
        platforms = platforms,
        peripherals = ["uart"],
        extra_cflags = [
            "-DLOG_TO_SERIAL",
        ],
    ).build()
