// automatically generated pin definitions, do not edit
// generated by /home/jelson/projects/rulos/src/util/makepins.py


#if defined(GPIOA)

static const gpio_pin_t GPIO_A0 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_A1 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_A2 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_A3 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_A4 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_A5 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_A6 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_A7 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_A8 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_A9 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_A10 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_A11 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_A12 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_A13 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_A14 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_A15 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_15,
};

#endif


#if defined(GPIOB)

static const gpio_pin_t GPIO_B0 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_B1 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_B2 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_B3 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_B4 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_B5 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_B6 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_B7 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_B8 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_B9 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_B10 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_B11 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_B12 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_B13 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_B14 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_B15 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_15,
};

#endif


#if defined(GPIOC)

static const gpio_pin_t GPIO_C0 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_C1 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_C2 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_C3 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_C4 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_C5 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_C6 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_C7 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_C8 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_C9 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_C10 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_C11 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_C12 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_C13 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_C14 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_C15 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_15,
};

#endif


#if defined(GPIOD)

static const gpio_pin_t GPIO_D0 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_D1 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_D2 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_D3 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_D4 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_D5 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_D6 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_D7 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_D8 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_D9 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_D10 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_D11 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_D12 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_D13 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_D14 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_D15 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_15,
};

#endif


#if defined(GPIOE)

static const gpio_pin_t GPIO_E0 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_E1 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_E2 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_E3 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_E4 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_E5 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_E6 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_E7 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_E8 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_E9 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_E10 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_E11 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_E12 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_E13 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_E14 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_E15 = {
   .port = GPIOE,
   .pin = LL_GPIO_PIN_15,
};

#endif


#if defined(GPIOF)

static const gpio_pin_t GPIO_F0 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_F1 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_F2 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_F3 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_F4 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_F5 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_F6 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_F7 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_F8 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_F9 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_F10 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_F11 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_F12 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_F13 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_F14 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_F15 = {
   .port = GPIOF,
   .pin = LL_GPIO_PIN_15,
};

#endif


#if defined(GPIOG)

static const gpio_pin_t GPIO_G0 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_G1 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_G2 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_G3 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_G4 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_G5 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_G6 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_G7 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_G8 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_G9 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_G10 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_G11 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_G12 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_G13 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_G14 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_G15 = {
   .port = GPIOG,
   .pin = LL_GPIO_PIN_15,
};

#endif


#if defined(GPIOH)

static const gpio_pin_t GPIO_H0 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_H1 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_H2 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_H3 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_H4 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_H5 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_H6 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_H7 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_H8 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_H9 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_H10 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_H11 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_H12 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_H13 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_H14 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_H15 = {
   .port = GPIOH,
   .pin = LL_GPIO_PIN_15,
};

#endif
