// automatically generated pin definitions, do not edit
// generated by /home/jelson/projects/rocket/src/util/makepins.py


#if defined(GPIOA)

static const gpio_pin_t GPIO_A0 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_A1 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_A2 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_A3 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_A4 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_A5 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_A6 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_A7 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_A8 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_A9 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_A10 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_A11 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_A12 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_A13 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_A14 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_A15 = {
   .port = GPIOA,
   .pin = LL_GPIO_PIN_15,
};

#endif


#if defined(GPIOB)

static const gpio_pin_t GPIO_B0 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_B1 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_B2 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_B3 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_B4 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_B5 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_B6 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_B7 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_B8 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_B9 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_B10 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_B11 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_B12 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_B13 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_B14 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_B15 = {
   .port = GPIOB,
   .pin = LL_GPIO_PIN_15,
};

#endif


#if defined(GPIOC)

static const gpio_pin_t GPIO_C0 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_C1 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_C2 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_C3 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_C4 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_C5 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_C6 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_C7 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_C8 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_C9 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_C10 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_C11 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_C12 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_C13 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_C14 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_C15 = {
   .port = GPIOC,
   .pin = LL_GPIO_PIN_15,
};

#endif


#if defined(GPIOD)

static const gpio_pin_t GPIO_D0 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_0,
};


static const gpio_pin_t GPIO_D1 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_1,
};


static const gpio_pin_t GPIO_D2 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_2,
};


static const gpio_pin_t GPIO_D3 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_3,
};


static const gpio_pin_t GPIO_D4 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_4,
};


static const gpio_pin_t GPIO_D5 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_5,
};


static const gpio_pin_t GPIO_D6 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_6,
};


static const gpio_pin_t GPIO_D7 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_7,
};


static const gpio_pin_t GPIO_D8 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_8,
};


static const gpio_pin_t GPIO_D9 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_9,
};


static const gpio_pin_t GPIO_D10 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_10,
};


static const gpio_pin_t GPIO_D11 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_11,
};


static const gpio_pin_t GPIO_D12 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_12,
};


static const gpio_pin_t GPIO_D13 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_13,
};


static const gpio_pin_t GPIO_D14 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_14,
};


static const gpio_pin_t GPIO_D15 = {
   .port = GPIOD,
   .pin = LL_GPIO_PIN_15,
};

#endif
