ROCKET_ROOT := ../..

MCU := atmega8
BOARD := CUSTOM
TARGET := audiotest
#EXTRA_AVR_CFLAGS :=  -DCRYSTAL=12000000
EXTRA_AVR_LDFLAGS := -lm

TARGET_OBJECTS := \
	audiotest.o


include $(ROCKET_ROOT)/Makefile.common

