#!/usr/bin/python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../../build-tools")
from BuildRules import *

RulosBuildTarget(
    name = "dualrocket-cpu0",
    sources = ["rocket.c"],
    extra_cflags = [
        "-DLOG_TO_SERIAL"
    ],
    peripherals = "rocket 7seg_panel display_rtc hpam audio adc rasters joystick joystick_adc uart input_controller remote_keyboard",
    platforms = [
        SimulatorPlatform(
            extra_peripherals="keypad",
            extra_cflags=[
                "-DBOARDCONFIG_ROCKET0",

                # Change SIM_CFLAGS to NETROCKET to debug remote bbufs
                #"-DBOARDCONFIG_NETROCKET",
            ],
        ),

        ## Uncomment this block for classic LPEM talking to an EPB
#        AvrPlatform(
#            "atmega1284p",
#            extra_cflags = [
#                "-DBOARDCONFIG_ROCKET0",
#                "-DBOARD_LPEM",
#            ],
#            extra_peripherals="7seg_panel_hardware keypad",
#        ),

        ## Uncomment this block for LPEM2 with remote bbufs
        AvrPlatform(
            "atmega1284p",
            extra_cflags = [
                "-DBOARDCONFIG_NETROCKET",
                "-DBOARD_LPEM2",
            ],
            extra_peripherals="twi",
        ),
    ],
).build()
