 #
 # This file is part of RulOS, Ravenna Ultra-Low-Altitude Operating
 # System -- the free, open-source operating system for microcontrollers.
 #
 # Written by Jon Howell (jonh@jonh.net) and Jeremy Elson (jelson@gmail.com),
 # May 2009.
 #
 # This operating system is in the public domain.  Copyright is waived.
 # All source code is completely free to use by anyone for any purpose
 # with no restrictions whatsoever.
 #
 # For more information about the project, see: www.jonh.net/rulos
 #

ROCKET_ROOT := ../..

PLATFORMS := avr
PERIPHERALS := 7seg_panel joystick adc hpam rocket input_controller audio sdcard spi rasters display_rtc
MCU := atmega328p
BOARD := PCB11
TARGET := hpamtest

TARGET_OBJECTS := \
	hpamtest.o


include $(ROCKET_ROOT)/Makefile.common

