#!/usr/bin/python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../build-tools")
from BuildRules import *

RulosBuildTarget(
    name = "flashcard",
    sources = [
        "flashcard.c",
    ],
    platforms = [
        AvrPlatform(
            "atmega1284p",
            extra_cflags = [
                "-DBOARDCONFIG_DEFAULT",
                "-DBOARD_FLASHCARD",
            ],
        ),
    ],
    peripherals = "uart led_matrix_single keypad lcd_12232 eeprom input_controller sdcard spi ",
    extra_converters = [
        SpecialRules.Converter(
            dependent_source = "src/app/flashcard/flashcard.c",
            intermediate_file = "src/app/flashcard/starbitmaps.ch",
            action = "star/ledmaps.py $TARGET star",
            script_input = cwd_to_project_root(glob.glob("star/*.png")),
        )
    ],
).build()

#$(AVR_OBJDIR)/app/flashcard.o: flashcard.c flashcard.c $(AVR_OBJDIR)/starbitmaps.ch
#
#%/starbitmaps.ch: star/*.png star/ledmaps.py
#	star/ledmaps.py $@ star

