#!/usr/bin/python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../../util")
from build_tools import *

#BOARD = "-DBOARD_GPS_TEST_RIG_REV_B"
#CHIP = "stm32f303xb"

BOARD = "-DBOARD_LTETAG_DEV_REV_A"
CHIP = "stm32g0b1xe"

RulosBuildTarget(
    name = "lowlevel",
    sources = ["lowlevel.c"],
    extra_cflags = [
        "-DLOG_TO_SERIAL",
        BOARD,
    ],
    platforms = [
        ArmStmPlatform(CHIP)
    ],
    peripherals = "uart sdcard2"
).build()


RulosBuildTarget(
    name = "fattest",
    sources = ["fattest.c"],
    extra_cflags = [
        "-DLOG_TO_SERIAL",
        BOARD,
    ],
    platforms = [
        ArmStmPlatform(CHIP)
    ],
    peripherals = "uart fatfs sdcard2"
).build()

RulosBuildTarget(
    name = "writeread",
    sources = ["writeread.c"],
    peripherals = "uart fatfs",
    extra_cflags = [
        "-DLOG_TO_SERIAL",
        "-DFF_USE_MKFS=1",
    ],
    platforms = [
        ArmStmPlatform(
            CHIP,
            extra_cflags = [
                BOARD,
            ],
            extra_peripherals = "sdcard2",
        ),
        SimulatorPlatform(
            extra_peripherals = "sdcardsim",
            extra_cflags = [
            ],
        )
    ],
).build()
