ROCKET_ROOT := ../..

MCU := atmega8
TARGET := timertest
BOARD := CUSTOM
EXTRA_AVR_CFLAGS := -DCRYSTAL=12000000 -DTIMING_DEBUG

TARGET_OBJECTS := \
	timertest.o




include $(ROCKET_ROOT)/Makefile.common

