#!/usr/bin/python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../../util")
from build_tools import *

RulosBuildTarget(
    name = "rocket6line_dongle",
    sources = ["dongle.c"],
    extra_cflags = [
        "-DLOG_TO_SERIAL",
        "-DBOARDCONFIG_UNIROCKET",
        "-DROCKET6LINE_REV_B",
        "-DDONGLE_BOARD_ID=3",
    ],
    platforms = [ ArmStmPlatform("stm32f303x8") ],
    peripherals = "uart 7seg_panel twi rocket6line",
).build()

RulosBuildTarget(
    name = "rocket6line_test",
    sources = ["test.c"],
    extra_cflags = [
        "-DLOG_TO_SERIAL",
        "-DBOARDCONFIG_UNIROCKET",
        "-DROCKET6LINE_REV_B",
    ],
    platforms = [ ArmStmPlatform("stm32f303x8") ],
    peripherals = "uart 7seg_panel rocket6line",
).build()
