#!/bin/sh

# Auto-formats all code that ends in .c or .h that's been changed in subversion.
# I should have called it "g4 fix".

svn status \
    | egrep '^M|A' \
    | cut -c9- \
    | grep '.*\.h$\|.*\.c$' \
    | grep -v vendor_libraries \
    | xargs clang-format -i --style=google --verbose

exit

# Or, to autoformat everything, remove the exit above
find . -name '*.[ch]' -type f -print \
    | fgrep -v /obj. \
    | grep -v vendor_libraries \
    | xargs clang-format -i --style=google --verbose

