#!/usr/bin/python3
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../../build-tools")
from BuildRules import *

for id in list(range(0,4))+list(range(7,12)):
    RulosBuildTarget(
      name = f"rocketdongle/address_{id}",
      sources = ["rocketdongle.c"],
      extra_cflags = ["-DBOARDCONFIG_ROCKET0", "-DDONGLE_BOARD_ID="+str(id), "-DLOG_TO_SERIAL=UART0"],
      platforms = [
        SimulatorPlatform(),
        AvrPlatform("atmega328", extra_cflags=["-DBOARD_DONGLE_REVB"], extra_peripherals="twi 7seg_panel_hardware"),
      ],
      peripherals = "7seg_panel uart"
      ).build()
