#!/usr/bin/python3
#
# Copyright (C) 2009 Jon Howell (jonh@jonh.net) and Jeremy Elson
# (jelson@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
sys.path.insert(0, "../../../build-tools")
from BuildRules import *

for chip in ["stm32f303xb", "stm32g431x8"]:
    RulosBuildTarget(
        name = "uarttest",
        sources = ["uarttest.c"],
        platforms = [ArmStmPlatform(chip)],
        peripherals = ["uart"],
        extra_cflags = [
            "-DLOG_TO_SERIAL=UART0",
        ],
    ).build()

for mcu in ["atmega328", "atmega328p", "atmega1284", "attiny84", "attiny85"]:
    RulosBuildTarget(
        name = "uarttest",
        sources = ["uarttest.c"],
        platforms = [AvrPlatform(mcu)],
        peripherals = ["uart"],
        extra_cflags = [
            "-DLOG_TO_SERIAL=UART0",
        ],
    ).build()
